Adds Title to the readme
Emmanuelaaron/re-former pull request #1
Opened 2020-06-29 15:39 UTC by Emmanuelaaron

gg

2020-06-30 04:05 UTC, maelfosso requested changes
# Changes required :red_circle:

Hello,

Thank you for this job! 
It's not over yet but you are on the right path for a good ending. Only a few things to change before moving forward.

Kindly read the comment left below to know more about the things to change and submit back a new code review request

Mael FOSSO

2020-06-30 04:05 UTC, maelfosso commented on app/controllers/users_controller.rb
> +      render new_user_path
The user should stay on the same page with the list of errors

2020-06-30 04:05 UTC, maelfosso commented on config/routes.rb
> +  post 'users/new', to: "users#new"
Why have you added this line?
Posting data from form will go into the `:create` action.

2020-06-30 04:05 UTC, maelfosso commented on app/views/users/_form.html.erb
> +<% end %>
It's always better to use `action=users_path` instead of `/users`

2020-06-30 04:05 UTC, maelfosso commented on app/views/users/_form.html.erb
> +<% end %>
Same thing concerning `form_tag("/users"...)`

2020-07-09 23:18 UTC, uryelah requested changes
Hi **Tesh Admasu & Isabirye Isabirye**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with the fixes! You're just missing one of them, check the points below carefully and good coding! 💪 

# Required Changes 🏗️ 🐛 💡

- [x] Make sure to Capitalize your commits and write them in the imperative tense.

2020-07-09 23:18 UTC, uryelah commented on app/controllers/users_controller.rb
> +      render new_user_path
- [ ] In here you need to render the :new action, not path, to follow rails conventions.

2020-07-09 23:18 UTC, uryelah commented on app/controllers/users_controller.rb
> +      render 'new'
- [ ] Prefer symbols instead of strings, it's more ruby-like.
- [ ] Here you should render the edit action, not the new action.

2020-07-09 23:18 UTC, uryelah commented
-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-07-13 04:57 UTC, Teshager21 commented
Implement all the feedback from the TSE.

2020-07-13 19:38 UTC, wathigo approved these changes
### Approved :heavy_check_mark: 
Great work guys :clap:
 
Consider implementing the optional suggestion :point_down:  before moving on
**You  may proceed to the next project.**

**Good luck :four_leaf_clover: 
Simon Wathigo**

2020-07-13 19:38 UTC, wathigo commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path
**OPTIONAL**
* Redirect to `edit_user_path` if user was saved.

2020-07-13 19:42 UTC, merged